import {readdir,stat,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
async function walk(dir){const files=[];for(const item of await readdir(dir,{withFileTypes:true})){const file=path.join(dir,item.name);if(item.isDirectory())files.push(...await walk(file));else files.push({file:file.replaceAll('\\','/'),bytes:(await stat(file)).size});}return files;}
const files=await walk('public'),types={};
for(const f of files){const type=path.extname(f.file)||'(none)';types[type]=(types[type]??0)+f.bytes;}
const mb=n=>(n/1024/1024).toFixed(2)+' MiB';
const pairs=files.filter(f=>f.file.endsWith('.png')&&files.some(g=>g.file===f.file.replace(/\.png$/,'.webp')));
const report=`# Audit distribučních podkladů\n\nGenerováno příkazem \`node scripts/audit-assets.mjs\`. Jde o obsah public, nikoli skutečný první síťový download. Vite jej celý kopíruje do buildu; prohlížeč obrázky stahuje až podle jejich použití.\n\nCelkem: ${files.length} souborů, ${mb(files.reduce((n,f)=>n+f.bytes,0))}.\n\n| Typ | Velikost |\n| --- | ---: |\n${Object.entries(types).sort((a,b)=>b[1]-a[1]).map(([type,bytes])=>`| ${type} | ${mb(bytes)} |`).join('\n')}\n\nPNG se stejně pojmenovaným WebP: ${pairs.length}, PNG celkem ${mb(pairs.reduce((n,f)=>n+f.bytes,0))}. To jsou kandidáti k prověření, nikoli automaticky bezpečně odstranitelné soubory.\n\n## Největší soubory\n\n| Soubor | Velikost |\n| --- | ---: |\n${files.sort((a,b)=>b.bytes-a.bytes).slice(0,20).map(f=>`| ${f.file} | ${mb(f.bytes)} |`).join('\n')}\n\n## Pořadí přípravy distribuce\n\n1. Zachovat současný web a oddělit editační zdroje od runtime assetů podle skutečných referencí, včetně dynamických názvů.\n2. Změřit čistý start a první kapitolu v síťovém panelu: přenesené bajty, čas do hratelnosti a načítání dalších kapitol.\n3. Rozdělit obsah kapitol pomocí dynamických importů, další kapitolu přednačítat před přechodem. Obrázky komiksů načítat jen před jejich použitím.\n4. Zavést společné herní jádro a adaptéry web/Telegram/Poki/CrazyGames; balance stránku dodávat pouze správci na webu.\n5. Teprve pak zapojit skutečné rewarded SDK podle aktuálních pravidel platformy; odměnu udělit pouze po potvrzení dokončené reklamy.\n\nTento audit neprokazuje limit první hratelné verze a nemění reklamy ani herní assety.\n`;
await mkdir('docs',{recursive:true});await writeFile('docs/distribution-assets-audit.md',report);console.log(report.split('\n').slice(0,7).join('\n'));
