const full={rows:7,cols:6,types:5};
const corners={...full,mask:Array.from({length:42},(_,i)=>![0,5,36,41].includes(i))};
export const airlockRepairs=[
 {id:'airlock-power',moves:20,room:'AIRLOCK',name:'Service power',icon:'ϟ',x:11,y:27,thought:"The emergency lamps are still holding. Let's restore the service panel before we touch the hatches.",lesson:'A little more light',objective:'Match 24 energy crystals to restore service power.',target:24,targetType:1,action:'Restore service power',result:'Service power restored. The airlock controls and work lights are back online.',level:full},
 {id:'airlock-inner-hatch',moves:12,room:'AIRLOCK',name:'Inner hatch',icon:'▣',x:28,y:36,thought:'This hatch separates the cabin from the airlock. It needs to close properly before I test the outer seals.',lesson:'A safe barrier',objective:'Match any 36 pieces to repair the inner hatch.',target:36,targetType:null,action:'Secure the inner hatch',result:'The inner hatch closes securely. The cabin can be isolated from the airlock.',level:corners},
 {id:'airlock-seals',moves:12,room:'AIRLOCK',name:'Airlock seals',icon:'◎',x:55,y:34,thought:'The inner hatch is secure. New seals will keep the outside cold away from the cabin.',lesson:'Holding steady',objective:'Match any 42 pieces to restore the airlock seals.',target:42,targetType:null,action:'Seal the airlock',result:'Pressure test passed. The outer hatch is sealed and its green indicator is on. Airlock secured.',level:corners,exterior:'./scenes/exterior-sealed.webp'},
];
export const airlockLogs=[
 {id:'airlock-service-light',repair:'airlock-power',title:'A little more light',text:"The service lights reveal a thin, branching scorch mark along the outer frame. It doesn't look like damage from the rocks. I'll inspect it when the hull camera is working."},
 {id:'airlock-inner-safe',repair:'airlock-inner-hatch',title:'One safe room at a time',text:'The inner hatch locks with a familiar, reassuring click. One more barrier between me and the cold outside. This ship is beginning to feel like shelter again.'},
 {id:'airlock-pressure-safe',repair:'airlock-seals',title:'Holding steady',text:'Pressure is holding. The airlock is airtight again. Whatever remains on the repair list, the cold outside can stay outside. One more step toward following that signal.'},
].map((e,i)=>({...e,source:'Personal log',time:`After landing / Airlock ${i+1}`,unlockAt:i+1}));
