import {AnalyticsControls,AnalyticsInsights} from './AnalyticsQuality.jsx';
import {fetchAnalytics,markAnalyticsTester} from './analyticsCloud.js';
import {excludeTesters,visitGroups,campaignKey,campaignSelection} from './analyticsReport.js';
import CountryStats from './CountryStats.jsx';
import {fetchCampaignStats} from './campaignTracking.js';
import {legacyRules,reportVersions,filterRules,latestAttempts,durationLabel,assistanceLabel,missingObjectives,funnelPercent} from './balanceReport.js';
import {attemptsForDay} from './balancePeriod.js';
import {fetchPlayerStats} from './playerPresence.js';
import {fetchBalanceReport,flushBalance,balanceCloudStatus,startBalanceCloud} from './balanceCloud.js';
import {readQueue} from './balanceOutbox.js';
import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {levelCatalog} from './levelCatalog.js';
import {readAttempts,summarizeAttempts} from './balanceTracking.js';
import './balance.css';
function Dashboard(){
 const [legacyCampaigns,setCampaigns]=useState([]),[legacyCampaignError,setCampaignError]=useState('');
 useEffect(()=>{let stopped=false;async function refresh(){if(document.hidden)return;try{const data=await fetchCampaignStats();if(!stopped){setCampaigns(data);setCampaignError('');}}catch{if(!stopped)setCampaignError('Měření návštěv není dostupné. Ověř přihlášení správce a migraci 026.');}}refresh();const timer=setInterval(refresh,30000);return()=>{stopped=true;clearInterval(timer);};},[]);
 const [day,setDay]=useState(''),[version,setVersion]=useState(''),[campaign,setCampaign]=useState('');
 const [analyticsData,setAnalyticsData]=useState(null),[analyticsError,setAnalyticsError]=useState(''),[testerBusy,setTesterBusy]=useState(false);
 const [includeTesters,setIncludeTesters]=useState(()=>{try{return localStorage.getItem('beyond-signal-report-testers')==='true';}catch{return false;}});
 const analyticsRevision=useRef(0),analyticsMounted=useRef(true);
 useEffect(()=>{try{localStorage.setItem('beyond-signal-report-testers',String(includeTesters));}catch{}},[includeTesters]);
 useEffect(()=>{
  let running=false;analyticsMounted.current=true;
  async function refresh(){if(document.hidden||running)return;running=true;const revision=analyticsRevision.current;
   try{const data=await fetchAnalytics();if(analyticsMounted.current&&revision===analyticsRevision.current){setAnalyticsData(data);setAnalyticsError('');}}
   catch(error){if(analyticsMounted.current&&revision===analyticsRevision.current)setAnalyticsError('Rozšířená analytika se neobnovila. Ověř migraci 028 a přihlášení správce. '+(error.message||''));}
   finally{running=false;}
  }
  refresh();const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);
  return()=>{analyticsMounted.current=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};
 },[]);
 async function markTester(id,tester){
  if(testerBusy)return;setTesterBusy(true);analyticsRevision.current++;
  try{await markAnalyticsTester(id,tester);analyticsRevision.current++;const data=await fetchAnalytics();if(analyticsMounted.current){setAnalyticsData(data);setAnalyticsError('');}}
  catch(error){if(analyticsMounted.current)setAnalyticsError('Označení nelze ověřit; obnov přehled. '+(error.message||''));}
  finally{analyticsRevision.current++;if(analyticsMounted.current)setTesterBusy(false);}
 }

 const reportRequest=useRef(false),reportCloudMode=useRef(true),reportMounted=useRef(true);
 const [reportUpdatedAt,setReportUpdatedAt]=useState(null);
 const [live,setLive]=useState(null),[liveError,setLiveError]=useState('');
 useEffect(()=>{let stopped=false;async function refresh(){if(document.hidden)return;try{const data=await fetchPlayerStats();if(!stopped){setLive(data);setLiveError('');}}catch{if(!stopped){setLive(null);setLiveError('Živé statistiky nejsou dostupné. Přihlas se účtem správce a ověř migraci 017.');}}}refresh();const timer=setInterval(refresh,30000);return()=>{stopped=true;clearInterval(timer);};},[]);
 const [allRows,setRows]=useState(readAttempts),[error,setError]=useState(''),[filter,setFilter]=useState(''),[onlyData,setOnlyData]=useState(true),[currentOnly,setCurrentOnly]=useState(true),[cloudBusy,setCloudBusy]=useState(false),[cloudState,setCloudState]=useState({...balanceCloudStatus,pending:readQueue().length}),[cloudLoaded,setCloudLoaded]=useState(false);
 useEffect(()=>{startBalanceCloud();const listener=e=>setCloudState(e.detail);window.addEventListener('balance-cloud-status',listener);return()=>window.removeEventListener('balance-cloud-status',listener);},[]);
 async function loadCloud(quiet=false){
  if(reportRequest.current)return;
  reportCloudMode.current=true;reportRequest.current=true;
  if(!quiet)setCloudBusy(true);setError('');
  try{const incoming=await fetchBalanceReport();if(reportMounted.current&&reportCloudMode.current){setRows(incoming);setCloudLoaded(true);setReportUpdatedAt(Date.now());}}
  catch{if(reportMounted.current&&reportCloudMode.current)setError(quiet?'Automatická obnova pokusů selhala; zobrazuji poslední načtené výsledky.':'Cloudový přehled nelze načíst. Přihlas se ve hře účtem správce; ověř migraci 016 a oprávnění v balance_admins.');}
  finally{reportRequest.current=false;if(reportMounted.current)setCloudBusy(false);}
 }
 useEffect(()=>{
  reportMounted.current=true;loadCloud();
  const refresh=()=>{if(!document.hidden&&reportCloudMode.current)loadCloud(true);};
  const timer=setInterval(refresh,30000);
  window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);
  return()=>{reportMounted.current=false;clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);};
 },[]);
 function download(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),campaign:campaign?JSON.parse(campaign):null,includeTesters,excludedTesters:includeTesters?[]:(analyticsData?.testers||[]),attempts:rows},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='beyond-signal-testovani.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function load(event){try{const data=JSON.parse(await event.target.files[0].text());const incoming=Array.isArray(data)?data:data.attempts;if(!Array.isArray(incoming)||incoming.length>100000||incoming.some(r=>!r||typeof r.level!=='string'||!['won','failed','quit','fault','exhausted'].includes(r.outcome)||!Number.isFinite(r.moves)))throw new Error();reportCloudMode.current=false;setCloudLoaded(false);setReportUpdatedAt(null);setRows(previous=>[...new Map([...previous,...incoming].map(r=>[r.attemptId??r.level+':'+r.at+':'+r.outcome,r])).values()]);setError('');}catch{setError('Soubor není platný export pokusů.');}event.target.value='';}
 const eligibleRows=analyticsData?excludeTesters(allRows,analyticsData.testers,includeTesters):allRows;
 const eligibleVisits=analyticsData?excludeTesters(analyticsData.visits,analyticsData.testers,includeTesters):[];
 const scope=campaignSelection(eligibleRows,eligibleVisits,campaign),rows=scope.attempts,visits=scope.visits;
 const campaignOptions=visitGroups(eligibleVisits);
 const unlinked=campaignSelection(eligibleRows,eligibleVisits).unlinked;
 const campaigns=analyticsData?visitGroups(visits):legacyCampaigns,campaignError=analyticsData?'':legacyCampaignError;
 const periodRows=attemptsForDay(rows,day), selectedRows=filterRules(periodRows,version);
 const versions=[...new Set([...reportVersions(rows),...(version?[version]:[])])];
 const latest=latestAttempts(rows,20);
 return <main><a href="./">← Hra</a><h1>Testování obtížnosti</h1><section className="live-stats" aria-label="Aktivita hráčů">{[["Právě ve hře",live?.active],["Aktivní dnes (UTC)",live?.today],["Zařízení celkem",live?.total],["Testy celkem · celé období",cloudBusy?null:rows.length]].map(([label,value])=><div key={label}><strong>{value??"—"}</strong><span>{label}</span></div>)}</section><p className="live-note">{liveError||"Aktivita i tabulka pokusů se obnovují každých 30 s · Právě ve hře = viditelná hra s odezvou za poslední 2 minuty. Počítáme prohlížeče/zařízení, nikoli unikátní osoby."}</p><p>{levelCatalog.length} hratelných levelů · {rows.length} záznamů celkem · {periodRows.length} ve vybraném období</p><p>{cloudLoaded&&reportUpdatedAt&&<>Poslední načtení pokusů: {new Date(reportUpdatedAt).toLocaleTimeString('cs-CZ')} · </>}{cloudLoaded?'Zobrazuji společná data ze Supabase.':'Zobrazuji místní data tohoto prohlížeče.'} Výsledky se odesílají automaticky i pro hosty; společný přehled načte pouze správce. Místní fronta: {cloudState.pending} · {cloudState.state==='saved'?'odesláno':cloudState.state==='sending'?'odesílání':'čeká na připojení nebo nastavení serveru'}.</p><p> Export od testerů lze sloučit importem; import mění pouze tento přehled. Neobsahují jméno ani e-mail. Úspěšnost počítá výhry a prohry, odchody a technické chyby jsou zvlášť. Rozpracované reklamní pokračování se při dokončení aktualizuje.</p><p>„Bez pomoci“ znamená bez pomůcek, nápovědy i +5 tahů. Hodnocení se objeví až od 20 pokusů a 5 známých zařízení; lidskou obtížnost nelze určit z několika her. Opakované pokusy jednoho člověka nejsou nezávislí testeři. Zařízení u levelu počítají různé identifikátory prohlížeče ve vybraných datech, včetně odchodů a chyb; místní export bez identifikátoru ukazuje —. Délka je medián dokončených pokusů včetně proher a vyčerpaných tahů, nikoli jen výher. Těsná prohra znamená nejvýše 10 % zbývajících jednotek u každého cíle včetně krytů a kruhů; neznámé cíle se do jmenovatele nepočítají. Vyčerpaný pokus se po pokračování může ještě změnit ve výhru. Změněné tahy a cíle porovnávej jako samostatné konfigurace.</p>
 {cloudState.error&&<p role="alert">Poslední chyba odeslání pokusů: {cloudState.error}</p>}
 <AnalyticsControls data={analyticsData} error={analyticsError} includeTesters={includeTesters} setIncludeTesters={setIncludeTesters} attempts={allRows} onMark={markTester} busy={testerBusy}/>
 <section className="recent-attempts" aria-label="Filtr kampaně"><h2>Vyhodnocení kampaně</h2><label>Kampaň a zdroj <select aria-label="Kampaň a zdroj" value={campaign} disabled={!analyticsData} onChange={e=>setCampaign(e.target.value)}><option value="">Všechny kampaně a zdroje</option>{campaignOptions.map(c=><option key={campaignKey(c)} value={campaignKey(c)}>{c.source} · {c.medium} · {c.campaign}</option>)}{campaign&&!campaignOptions.some(c=>campaignKey(c)===campaign)&&<option value={campaign}>Vybraná kampaň · bez návštěv</option>}</select></label><p>Filtr platí pro návštěvy, země, průchod úvodem, typ zařízení, poslední pokusy, obtížnost a export JSON. Živá aktivita a návraty zařízení zůstávají za všechny kampaně. Filtry dne a verze níže platí pouze pro tabulku obtížnosti.</p><p>Pokusy přiřazujeme podle ID pokusu i zařízení v návštěvě, nikoli podle všech her stejného hráče. {unlinked} pokusů nemá vazbu na načtené návštěvy; zůstávají pouze ve všech kampaních. Pokus pokračující přes více kampaní může být v každé z nich. Bounty se automaticky neoznačuje jako interní tester.</p>{campaign&&<p>Vybraná kampaň: {visits.length} návštěv · {rows.length} přiřazených záznamů pokusů. Prázdný výsledek může znamenat i dosud neodeslaná data.</p>}</section>
 <section className="recent-attempts" aria-label="Návštěvy a kampaně"><h2>Návštěvy a reklamní kampaně</h2><p>Celé období od zapnutí měření. Relace se zachová při obnovení a přihlášení; po 30 minutách neaktivity vznikne nová. Nejde o unikátní osoby. Spuštěná minihra znamená otevřenou desku s energií; dokončení = alespoň jedna výhra. Procenta uvádějí podíl návštěv, nikoli osob. Další level znamená alespoň dva různé spuštěné levely; nemusí následovat po výhře. Zdroj vychází z UTM odkazu, sám nepotvrzuje placené kliknutí.</p>{campaignError?<p role="alert">{campaignError}</p>:<div className="recent-wrap"><table><thead><tr>{['Zdroj / kampaň','Návštěvy','Zařízení','Spustili minihru','Vyhráli level','Hráli další level','Bez spuštění','Pokusy'].map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{campaigns.map(c=><tr key={`${c.source}:${c.medium}:${c.campaign}`}><td>{c.source} · {c.medium}<small>{c.campaign}</small></td><td>{c.visits}</td><td>{c.devices}</td><td>{c.started}<small>{funnelPercent(c.started,c.visits)} návštěv</small></td><td>{c.won}<small>{funnelPercent(c.won,c.started)} ze spuštěných</small></td><td>{c.continued}<small>{funnelPercent(c.continued,c.started)} ze spuštěných</small></td><td>{Math.max(0,c.visits-c.started)}<small>{funnelPercent(Math.max(0,c.visits-c.started),c.visits)} návštěv</small></td><td>{c.attempts}</td></tr>)}</tbody></table>{!campaigns.length&&<p>Zatím žádné změřené návštěvy.</p>}</div>}</section>
 <CountryStats providedRows={analyticsData?visitGroups(visits,['country','source','medium','campaign']):null}/>
 <AnalyticsInsights data={analyticsData} visits={visits} allVisits={eligibleVisits}/>
 <section className="recent-attempts" aria-label="Poslední pokusy"><h2>Poslední zaznamenané pokusy</h2><p>Čas odehrání v českém časovém pásmu. Posledních 20 pokusů vybrané kampaně; bez filtru dne a verze tabulky. Délka zahrnuje čekání a čas v neaktivní kartě. Pomůcky nezahrnují nálože vytvořené na desce. U starších záznamů mohou údaje chybět.</p><div className="recent-wrap"><table><thead><tr><th>Odehráno</th><th>Level</th><th>Zařízení</th><th>Výsledek</th><th>Délka</th><th>Tahy použité / limit</th><th>Zbývá tahů</th><th>Pomoc</th><th>Chybělo do cíle</th><th>Verze pravidel</th></tr></thead><tbody>{latest.map((a,i)=>{const r=levelCatalog.find(r=>r.id===a.level);return <tr key={a.attemptId??i}><td>{new Date(a.at).toLocaleString('cs-CZ',{timeZone:'Europe/Prague'})}</td><td>{r?`${r.number}. ${r.name}`:a.level}</td><td title={a.reporter||''}>{a.reporter?.slice(0,8)||'—'}</td><td>{{won:'Výhra',failed:'Prohra',exhausted:'Došly tahy',quit:'Odchod',fault:'Technická chyba'}[a.outcome]??a.outcome}</td><td>{durationLabel(a.durationMs)}</td><td>{a.moves??'—'} / {a.budget??'—'}{a.baseBudget!=null&&a.baseBudget!==a.budget&&<small>Základ: {a.baseBudget}</small>}</td><td>{a.remaining??'—'}</td><td>{assistanceLabel(a)}</td><td>{missingObjectives(a)}</td><td>{a.build||'Starší · bez verze'}</td></tr>;})}</tbody></table></div>{!latest.length&&<p>Zatím žádné pokusy s platným časem.</p>}</section>
 <div className="controls"><label>Verze pravidel <select aria-label="Verze pravidel" value={version} onChange={e=>setVersion(e.target.value)}><option value="">Všechny verze</option>{versions.map(v=><option key={v} value={v}>{v===legacyRules?'Starší · bez verze':v}</option>)}</select></label><label>Období <select aria-label="Období" value={day?"day":"all"} onChange={e=>setDay(e.target.value==="all"?"":new Intl.DateTimeFormat("sv-SE",{timeZone:"Europe/Prague"}).format(new Date()))}><option value="all">Celé období</option><option value="day">Vybraný den</option></select></label>{day&&<label>Den <input aria-label="Den" type="date" value={day} onChange={e=>setDay(e.target.value)}/></label>}<small>Filtr dne: český čas (Europe/Prague)</small><button onClick={()=>{reportCloudMode.current=false;setRows(readAttempts());setCloudLoaded(false);setReportUpdatedAt(null);}}>Místní data</button><button disabled={cloudBusy} onClick={()=>loadCloud()}>{cloudBusy?'Načítání…':'Načíst všechny testery ze Supabase'}</button><button onClick={flushBalance}>Odeslat čekající pokusy</button><button onClick={download}>Export JSON</button><label className="upload">Import od testera<input type="file" accept="application/json,.json" onChange={load}/></label><input placeholder="Hledat level nebo oblast" value={filter} onChange={e=>setFilter(e.target.value)}/><label><input type="checkbox" checked={onlyData} onChange={e=>setOnlyData(e.target.checked)}/> Jen s daty</label><label><input type="checkbox" checked={currentOnly} onChange={e=>setCurrentOnly(e.target.checked)}/> Jen aktuální tahy a rozměry</label></div>{error&&<p role="alert">{error}</p>}
 <p>{selectedRows.length} záznamů po filtru kampaně, období a verze. Filtr aktuálních tahů a rozměrů se uplatňuje navíc pro každý level; nerozlišuje staré cíle se stejnými rozměry.</p><div className="table-wrap"><table><thead><tr>{['Level / oblast','Deska','Tahy','Zařízení','Délka (medián)','Pokusy','Výhry','Úspěšnost','Bez pomoci','Pomoc','Zbývá tahů při výhře','Odchody / chyby','Těsné prohry / měřené','Doporučení'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{levelCatalog.filter(r=>(r.name+' '+r.group+' '+r.id).toLowerCase().includes(filter.toLowerCase())).map(r=>{const stats=summarizeAttempts(currentOnly?selectedRows.filter(a=>a.baseBudget===r.moves&&a.configuration?.cols===r.cols&&a.configuration?.rows===r.rows&&a.configuration?.types===r.types):selectedRows,r.id);if(onlyData&&!stats.attempts&&!stats.quits&&!stats.faults)return null;const pct=n=>n==null?'—':n+' %';return <tr key={r.id}><td><strong>{r.number}. {r.name}</strong><small>{r.group} · {r.id}</small></td><td>{r.cols}×{r.rows}</td><td>{r.moves}</td><td>{stats.devices??'—'}</td><td>{durationLabel(stats.duration)}</td><td>{stats.attempts}</td><td>{stats.wins}</td><td>{pct(stats.rate)}</td><td>{pct(stats.cleanRate)} ({stats.cleanAttempts})</td><td>{pct(stats.help)}</td><td>{stats.remaining??'—'}</td><td>{stats.quits} / {stats.faults}</td><td>{stats.nearMisses} / {stats.measuredFailures}</td><td>{stats.verdict}</td></tr>;})}</tbody></table></div>
 <details><summary>Konfigurace zaznamenaných pokusů</summary><p>Pro porovnání při změně limitů použij surový export: budget, baseBudget, configuration, counts, remainingCovers, resonance, durationMs. Starší záznamy tyto údaje nemají.</p></details></main>;
}
createRoot(document.getElementById('root')).render(<Dashboard/>);
