import {fetchPlayerStats} from './playerPresence.js';
import {fetchBalanceReport,flushBalance,balanceCloudStatus,startBalanceCloud} from './balanceCloud.js';
import {readQueue} from './balanceOutbox.js';
import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {levelCatalog} from './levelCatalog.js';
import {readAttempts,summarizeAttempts} from './balanceTracking.js';
import './balance.css';
function Dashboard(){
 const [live,setLive]=useState(null),[liveError,setLiveError]=useState('');
 useEffect(()=>{let stopped=false;async function refresh(){if(document.hidden)return;try{const data=await fetchPlayerStats();if(!stopped){setLive(data);setLiveError('');}}catch{if(!stopped){setLive(null);setLiveError('Živé statistiky nejsou dostupné. Přihlas se účtem správce a ověř migraci 017.');}}}refresh();const timer=setInterval(refresh,30000);return()=>{stopped=true;clearInterval(timer);};},[]);
 const [rows,setRows]=useState(readAttempts),[error,setError]=useState(''),[filter,setFilter]=useState(''),[onlyData,setOnlyData]=useState(false),[currentOnly,setCurrentOnly]=useState(true),[cloudBusy,setCloudBusy]=useState(false),[cloudState,setCloudState]=useState({...balanceCloudStatus,pending:readQueue().length}),[cloudLoaded,setCloudLoaded]=useState(false);
 useEffect(()=>{startBalanceCloud();const listener=e=>setCloudState(e.detail);window.addEventListener('balance-cloud-status',listener);return()=>window.removeEventListener('balance-cloud-status',listener);},[]);
 async function loadCloud(){setCloudBusy(true);setError('');try{const incoming=await fetchBalanceReport();setRows(incoming);setCloudLoaded(true);}catch{setError('Cloudový přehled nelze načíst. Přihlas se ve hře účtem správce; ověř migraci 016 a oprávnění v balance_admins.');}finally{setCloudBusy(false);}}
 function download(){const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),attempts:rows},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='beyond-signal-testovani.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function load(event){try{const data=JSON.parse(await event.target.files[0].text());const incoming=Array.isArray(data)?data:data.attempts;if(!Array.isArray(incoming)||incoming.length>100000||incoming.some(r=>!r||typeof r.level!=='string'||!['won','failed','quit','fault','exhausted'].includes(r.outcome)||!Number.isFinite(r.moves)))throw new Error();setRows(previous=>[...new Map([...previous,...incoming].map(r=>[r.attemptId??r.level+':'+r.at+':'+r.outcome,r])).values()]);setError('');}catch{setError('Soubor není platný export pokusů.');}event.target.value='';}
 return <main><a href="./">← Hra</a><h1>Testování obtížnosti</h1><section className="live-stats" aria-label="Aktivita hráčů">{[["Právě ve hře",live?.active],["Aktivní dnes (UTC)",live?.today],["Zařízení celkem",live?.total],["Pokusy dnes (UTC)",live?.attemptsToday]].map(([label,value])=><div key={label}><strong>{value??"—"}</strong><span>{label}</span></div>)}</section><p className="live-note">{liveError||"Obnova každých 30 s · Právě ve hře = viditelná hra s odezvou za poslední 2 minuty. Počítáme prohlížeče/zařízení, nikoli unikátní osoby."}</p><p>{levelCatalog.length} hratelných levelů · {rows.length} záznamů v tomto přehledu</p><p>{cloudLoaded?'Zobrazuji společná data ze Supabase.':'Zobrazuji místní data tohoto prohlížeče.'} Výsledky se odesílají automaticky i pro hosty; společný přehled načte pouze správce. Místní fronta: {cloudState.pending} · {cloudState.state==='saved'?'odesláno':cloudState.state==='sending'?'odesílání':'čeká na připojení nebo nastavení serveru'}.</p><p> Export od testerů lze sloučit importem; import mění pouze tento přehled. Neobsahují jméno ani e-mail. Úspěšnost počítá výhry a prohry, odchody a technické chyby jsou zvlášť. Rozpracované reklamní pokračování se při dokončení aktualizuje.</p><p>„Bez pomoci“ znamená bez pomůcek, nápovědy i +5 tahů. Hodnocení se objeví až od 20 pokusů; lidskou obtížnost nelze určit z několika her. Opakované pokusy jednoho člověka nejsou nezávislí testeři. Změněné tahy a cíle porovnávej jako samostatné konfigurace.</p>
 <div className="controls"><button onClick={()=>{setRows(readAttempts());setCloudLoaded(false);}}>Místní data</button><button disabled={cloudBusy} onClick={loadCloud}>{cloudBusy?'Načítání…':'Načíst všechny testery ze Supabase'}</button><button onClick={flushBalance}>Odeslat čekající pokusy</button><button onClick={download}>Export JSON</button><label className="upload">Import od testera<input type="file" accept="application/json,.json" onChange={load}/></label><input placeholder="Hledat level nebo oblast" value={filter} onChange={e=>setFilter(e.target.value)}/><label><input type="checkbox" checked={onlyData} onChange={e=>setOnlyData(e.target.checked)}/> Jen s daty</label><label><input type="checkbox" checked={currentOnly} onChange={e=>setCurrentOnly(e.target.checked)}/> Jen aktuální tahy a rozměry</label></div>{error&&<p role="alert">{error}</p>}
 <div className="table-wrap"><table><thead><tr>{['Level / oblast','Deska','Tahy','Pokusy','Výhry','Úspěšnost','Bez pomoci','Pomoc','Zbývá tahů při výhře','Odchody / chyby','Doporučení'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{levelCatalog.filter(r=>(r.name+' '+r.group+' '+r.id).toLowerCase().includes(filter.toLowerCase())).map(r=>{const stats=summarizeAttempts(currentOnly?rows.filter(a=>a.baseBudget===r.moves&&a.configuration?.cols===r.cols&&a.configuration?.rows===r.rows&&a.configuration?.types===r.types):rows,r.id);if(onlyData&&!stats.attempts&&!stats.quits&&!stats.faults)return null;const pct=n=>n==null?'—':n+' %';return <tr key={r.id}><td><strong>{r.name}</strong><small>{r.group} · {r.id}</small></td><td>{r.cols}×{r.rows}</td><td>{r.moves}</td><td>{stats.attempts}</td><td>{stats.wins}</td><td>{pct(stats.rate)}</td><td>{pct(stats.cleanRate)} ({stats.cleanAttempts})</td><td>{pct(stats.help)}</td><td>{stats.remaining??'—'}</td><td>{stats.quits} / {stats.faults}</td><td>{stats.verdict}</td></tr>;})}</tbody></table></div>
 <details><summary>Konfigurace zaznamenaných pokusů</summary><p>Pro porovnání při změně limitů použij surový export: budget, baseBudget, configuration, counts, remainingCovers, resonance, durationMs. Starší záznamy tyto údaje nemají.</p></details></main>;
}
createRoot(document.getElementById('root')).render(<Dashboard/>);
