import {levelCatalog,levelGroups} from './levelCatalog.js';
import React,{useEffect,useRef} from 'react';
import {useLanguage} from './i18n/Language.jsx';
import {chaptersFor,chapterSectionOpen} from './chapters.js';
export default function Chapters({progress,onNavigate,onClose,onReplay}){
 const {language,t}=useLanguage(),ref=useRef(null);
 const chapters=chaptersFor(progress);
 const totalStars=ids=>ids.reduce((sum,id)=>sum+(progress.stars?.[id]??0),0);
 const chapterStars=c=>{const start=chapters.slice(0,c.number-1).reduce((n,c)=>n+c.total,0);return totalStars(levelCatalog.slice(start,start+c.total).map(r=>r.id));};
 const sectionStars=(c,s,i)=>totalStars((c.id==='ship'?levelGroups[i][1]:s.repairs).map(r=>r.id));
 useEffect(()=>{const opener=document.activeElement;ref.current.showModal();return()=>opener?.isConnected&&opener.focus();},[]);
 return <dialog ref={ref} className="chapters-dialog" onCancel={e=>{e.preventDefault();onClose();}} aria-labelledby="chapters-title"><button className="close" autoFocus onClick={onClose} aria-label={t('Close')}>×</button><h2 id="chapters-title">{language==='cs'?'Kapitoly':'Chapters'}</h2><div className="chapters-list">{chapters.map(c=><details key={c.id}><summary>{c.image&&<img src={`./scenes/${c.image}.webp`} alt="" loading="lazy"/>}<span>{String(c.number).padStart(2,'0')} · {language==='cs'?c.cs:c.en}</span><b>{c.done===c.total?'✓ ':''}{c.done}/{c.total} {!c.open?'🔒':''}<small className="chapter-stars">★ {chapterStars(c)} / {c.total*3}</small></b></summary>{c.partial&&<p>{language==='cs'?'Další obsah připravujeme.':'More content is in development.'}</p>}<div className="chapter-actions"><button disabled={!c.open} onClick={()=>onNavigate(c.done<c.total?c.next:c.entry)}>{language==='cs'?(c.done<c.total?'Pokračovat':'Navštívit'):(c.done<c.total?'Continue':'Visit')}</button>{c.sections.map((s,i)=><button key={s.scene} disabled={!chapterSectionOpen(progress,c,s.scene)} onClick={()=>onNavigate(s.scene)}>{t(s.title)} · {(progress[s.key]??0)===s.repairs.length?'✓ ':''}{progress[s.key]??0}/{s.repairs.length}<span className="chapter-stars">★ {sectionStars(c,s,i)} / {s.repairs.length*3}</span></button>)}{c.id==='ship'&&progress.finaleDone&&<button onClick={()=>onReplay('launch-check')}>{language==='cs'?'Předletová kontrola':'Launch check'} <span className="chapter-stars">★ {progress.stars?.['launch-check']??1} / 3</span></button>}{c.id==='aster'&&progress.elysiumRouteCompleted===1&&<button onClick={()=>onReplay('elysium-route')}>{language==='cs'?'Příletová trasa k Elysiu':'Elysium approach route'} <span className="chapter-stars">★ {progress.stars?.['elysium-route']??1} / 3</span></button>}</div></details>)}</div></dialog>;
}
