const full={rows:8,cols:7,types:6};
const corners={...full,mask:Array.from({length:56},(_,i)=>![0,6,49,55].includes(i))};
export const engineRepairs=[
 {id:'engine-cooling',room:'ENGINE ROOM',name:'Cooling circuit',icon:'◇',x:18,y:25,thought:"Before anything powers up, the cooling loop needs to hold. I'll replace the damaged pipes first.",lesson:'Keep your cool',objective:'Match 20 blue comets to restore the cooling circuit.',target:20,targetType:2,action:'Restore cooling',result:'The cooling loop is sealed and circulating.',level:full},
 {id:'engine-fuel',room:'ENGINE ROOM',name:'Fuel system',icon:'▣',x:80,y:26,thought:"The reserve tank survived. Reconnecting these lines will let us use the fuel already aboard.",lesson:'A reserve of hope',objective:'Match 20 fuel cells to reconnect the fuel system.',target:20,targetType:0,action:'Connect the fuel lines',result:'The reserve tank is connected and the fuel lines are secure.',level:corners},
 {id:'engine-power',room:'ENGINE ROOM',name:'Main power',icon:'ϟ',x:50,y:33,thought:"Cooling and fuel are ready. Let's restore the core housing and bring the main supply online.",lesson:'A beating heart',objective:'Match 22 energy crystals to restore main power.',target:22,targetType:1,action:'Power up the core',result:'The core is stable. Main power is restored in the engine room.',level:full},
 {id:'engine-drive',room:'ENGINE ROOM',name:'Engine assembly',icon:'◎',x:20,y:50,thought:"The drive coupling took the force of the landing. I'll rebuild it and secure the housing before the test.",lesson:'Built to move',objective:'Match 22 red energy orbs to restore the engine assembly.',target:22,targetType:5,action:'Restore the engine assembly',result:'The internal drive assembly is repaired and in standby. Launch remains locked.',level:corners},
 {id:'engine-test',room:'ENGINE ROOM',name:'Systems test',icon:'✓',x:80,y:48,thought:"One repaired console, then a controlled systems check. A working engine room is a step toward flight, not clearance to launch.",lesson:'Steady and ready',objective:'Match any 54 pieces to complete the engine-room systems test.',target:54,targetType:null,action:'Run the systems test',result:'Engine-room checks passed. Its red doorway is lit. All ship repairs and navigation must be complete before launch.',level:full},
];
export const engineLogs=[
 {id:'engine-cold',repair:'engine-cooling',title:'Circulation',text:"Coolant is moving through the pipes again. I can hear it beneath the emergency hum. A quiet beginning for a room built to move a ship."},
 {id:'engine-reserve',repair:'engine-fuel',title:'What we still have',text:"The reserve tank held through the landing. We do not have to search this moon for fuel. We just have to put what survived back to work."},
 {id:'engine-heart',repair:'engine-power',title:'A familiar heartbeat',text:"The core is glowing again. This is the power the ship redirected to protect the cockpit. Now I can begin giving it back."},
 {id:'engine-motion',repair:'engine-drive',title:'The promise of motion',text:"The drive coupling is secure. Standby is a long way from flying, but it is closer than we were. I will not ask these engines to lift an unfinished ship."},
 {id:'engine-checked',repair:'engine-test',title:'One part of the whole',text:"The engine-room checks passed. A sound hull and a verified route are required before launch. The beacon can wait a little longer while I finish the work."},
].map((e,i)=>({...e,source:'Personal log',time:`After landing / Engine room ${i+1}`,unlockAt:i+1}));
