import {spacedResonatorCovers} from './resonators.js';
export const rootTranslations={};
const text=(en,cs)=>(rootTranslations[en]=cs,en);
const title=text('The root chamber','Kořenová komora');
const labels=['Coolant charges','Energy modules','Navigation prisms','Root nodes','Luminous pollen','Living seeds'];
const csLabels=['chladicích náplní','energetických modulů','navigačních hranolů','kořenových uzlů','světelného pylu','živých semen'];
const rows=[
 ["air",text("Restore the breathing vents","Obnov dýchací průduchy"),text("The chamber is sealed. Open the old ventilation gates before we wake the instruments.","Komora je uzavřená. Než probudíme přístroje, otevřeme staré větrací průduchy."),text("Clean air moves through the root vault.","Kořenovou klenbou proudí čistý vzduch."),text("Air for visitors","Vzduch pro návštěvníky"),text("The expedition added air filters here. Whatever built this chamber made room for human visitors.","Výprava zde přidala vzduchové filtry. Tvůrce komory počítal i s lidskými návštěvníky."),[[0, 27], [3, 24]],25,22,68],
 ["record",text("Recover the expedition record","Obnov záznam výpravy"),text("Release the console covers and connect its memory to our navigation prism.","Uvolníme kryty konzole a připojíme její paměť k navigačnímu hranolu."),text("The console reveals a surviving expedition recording.","Konzole odhaluje dochovaný záznam výpravy."),text("They came willingly","Přišli dobrovolně"),text("The last recording contains no alarm. The team followed a guide into the sanctuary and left a return route for whoever found their beacon.","Poslední záznam neobsahuje poplach. Tým následoval průvodce do svatyně a zanechal zpáteční cestu pro toho, kdo najde jejich maják."),[[2, 30], [1, 24]],27,79,61],
 ["nursery",text("Rebalance the seed nursery","Vyvaž semennou komoru"),text("Restore the nursery flow without removing its living seeds. Their light carries the chamber rhythm.","Obnovíme proudění v semenné komoře, aniž bychom odebrali živá semena. Jejich světlo nese rytmus komory."),text("The protected seeds brighten behind the glass.","Chráněná semena se za sklem rozsvěcují."),text("A memory that grows","Paměť, která roste"),text("Each seed repeats a different fragment of the expedition call. The garden stores memories by growing them, not by copying a machine.","Každé semeno opakuje jinou část volání výpravy. Zahrada uchovává vzpomínky jejich pěstováním, nikoli kopírováním stroje."),[[5, 30], [0, 24]],28,28,34],
 ["voice",text("Tune the caretaker channel","Nalaď kanál správce"),text("Charge the ring with matches beside it. Translate the root pulses into a voice our radio can receive.","Nabijeme kruh spojováním vedle něj. Přeložíme kořenové impulzy do hlasu, který zachytí naše rádio."),text("A steady cyan pulse reaches the ship radio.","Stálý tyrkysový impulz dosahuje lodního rádia."),text("A voice beneath the roots","Hlas pod kořeny"),text("A calm reply arrives: visitors are safe; the path remembers them. The caretaker asks us to keep the return channel open before approaching.","Přichází klidná odpověď: návštěvníci jsou v bezpečí; cesta si je pamatuje. Správce nás žádá, abychom před příchodem zachovali zpáteční kanál."),[[3, 30], [4, 27]],30,55,43],
 ["door",text("Open the sanctuary threshold · HARD","Otevři práh svatyně · TĚŽKÉ"),text("Synchronise both rings and secure our route to the grove. Only then should the living door open.","Sladíme oba kruhy a zajistíme cestu do porostu. Teprve potom otevřeme živé dveře."),text("The root door opens a safe route toward the caretaker.","Kořenové dveře otevírají bezpečnou cestu ke správci."),text("An invitation, not a trap","Pozvání, ne past"),text("The door opens from both sides. Behind it, a warm light answers our beacon. We send our position to Elysium and prepare to meet the caretaker.","Dveře se otevírají z obou stran. Za nimi odpovídá našemu majáku teplé světlo. Odesíláme polohu Elysiu a chystáme se setkat se správcem."),[[2, 27], [4, 27], [5, 24]],33,77,35],
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>{
 const resonators=i===3?[{at:27,target:3}]:i===4?[{at:26,target:3},{at:45,target:4}]:[];
 const holes=i===1?[0,6,49,55]:[];
 const size=i>=3?64:56;
 return {id:'root-'+slug,name,lesson:name,thought,result,room:title,action:text('Activate the root system','Aktivuj systém kořenové komory'),icon:'✦',x,y,moves,tileSet:'night',resonators,
 level:{cols:i>=3?8:7,rows:8,types:6,mask:Array.from({length:size},(_,n)=>!holes.includes(n)&&!resonators.some(r=>r.at===n))},
 ice:i===0?[9,12,37,40]:i===1?[9,12,23,25]:i===2?[9,12,23,25,37,40]:i===3?[17,22,41,46]:[9,14,17,22,41,46,49,54],
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'.'+(i>=0?' Break all protective covers.':'')+(resonators.length?' Charge every resonator.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+csLabels[type]).join(', ')+'.'+(i>=0?' Rozbij všechny ochranné kryty.':'')+(resonators.length?' Nabij všechny rezonátory.':''))};
});
repairs.forEach(r=>{r.ice=spacedResonatorCovers(r.ice,r.resonators,r.level);});
export const rootDestination={nextScene:'night-sanctuary',nextLabel:'Enter the caretaker sanctuary →',title,key:'nightRootCompleted',system:'night-grove',chapter:text('CHAPTER 08 / THE NIGHT GARDEN','KAPITOLA 08 / NOČNÍ ZAHRADA'),hotspotOffset:0,image:'night-root',restoredImage:'night-root-restored',repairs,
 logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Night expedition log','Deník noční výpravy'),time:title,unlockAt:131+i})),
 complete:text('Channel restored. The caretaker awaits beyond the living door.','Kanál obnoven. Správce čeká za živými dveřmi.'),
 clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 34% 27% at '+r.x+'% '+r.y+'%, #000 30%, transparent 100%)')};
text('Enter the root chamber →','Vstup do kořenové komory →');text('Return to the luminous grove →','Zpět do světélkujícího porostu →');
