import {spacedResonatorCovers} from './resonators.js';
export const groveTranslations={};
const text=(en,cs)=>(groveTranslations[en]=cs,en);
const title=text('The luminous grove','Světélkující porost');
const labels=['Coolant charges','Energy modules','Navigation prisms','Root nodes','Luminous pollen','Living seeds'];
const csLabels=['chladicích náplní','energetických modulů','navigačních hranolů','kořenových uzlů','světelného pylu','živých semen'];
const rows=[
 ['sampler',text('Calibrate the field sampler','Seřiď terénní vzorkovač'),text('The landing glade is safe. Set the sampler to observe living pollen without draining its light.','Přistávací mýtina je bezpečná. Nastavíme vzorkovač tak, aby sledoval živý pyl, aniž by mu odebral světlo.'),text('The sampler opens a protected observation chamber.','Vzorkovač otevírá chráněnou pozorovací komoru.'),text('Observe, do not harvest','Pozorovat, ne sklízet'),text('The expedition left its collection limit beside the instrument: one small sample, then leave the flower untouched. Their care may be why the grove still answers.','Výprava nechala vedle přístroje limit odběru: jeden malý vzorek a květ nechat být. Možná právě díky jejich opatrnosti nám porost stále odpovídá.'),[[2,24],[4,24]],25,85,74],
 ['channels',text('Refill the grove channels','Naplň kanály porostu'),text('The shallow basin is dry. Restore its gates so water reaches the roots before we ask them to carry another signal.','Mělká nádrž je suchá. Obnovíme její stavidla, aby voda dorazila ke kořenům dříve, než je požádáme o další přenos signálu.'),text('Turquoise water flows through the terrace channels.','Tyrkysová voda proudí terasovými kanály.'),text('A measured flow','Odvážený proud'),text('The gate responds to a small adjustment. Roots along the basin brighten as water returns. The grove is not a fuel source; it is a living neighbour.','Stavidlo reaguje na malou úpravu. Kořeny podél nádrže se při návratu vody rozsvěcují. Porost není zdroj paliva, ale živý soused.'),[[0,30],[3,24]],27,22,64],
 ['bloom',text('Decode the pollen response','Rozlušti odpověď pylu'),text('The flower repeats our pulse with a delay. Release the instrument covers and compare its light pattern with the expedition recording.','Květ opakuje náš impulz se zpožděním. Uvolníme kryty přístroje a porovnáme světelný vzor se záznamem výpravy.'),text('The amber flower opens and releases a gentle cloud of light.','Jantarový květ se otevírá a uvolňuje jemný oblak světla.'),text('An echo that changes','Ozvěna, která se mění'),text('The reply is not an identical echo. A missing beat appears exactly where the human beacon paused. Someone taught this garden a fragment of their call sign.','Odpověď není totožná ozvěna. Vynechaný úder se objevuje přesně tam, kde se odmlčel lidský maják. Někdo tuto zahradu naučil část svého volacího znaku.'),[[4,30],[5,24]],28,86,40],
 ['resonance',text('Link the grove resonator','Propoj rezonátor porostu'),text('Match beside the ring to connect the flower pattern to the root network. Keep its rhythm gentle and our return channel open.','Spojováním vedle kruhu připojíme vzor květu ke kořenové síti. Zachováme jemný rytmus i otevřený zpáteční kanál.'),text('A cyan ring carries the decoded pattern into the roots.','Tyrkysový kruh přenáší rozluštěný vzor do kořenů.'),text('A borrowed voice','Vypůjčený hlas'),text('The resonator translates the light into a familiar expedition identifier. It contains no distress command. It points toward shelter deeper below the grove.','Rezonátor převádí světlo na známý identifikátor výpravy. Neobsahuje nouzový příkaz. Ukazuje k úkrytu hlouběji pod porostem.'),[[1,27],[3,27]],30,50,44],
 ['arch',text('Reveal the root passage · HARD','Odhal kořenový průchod · TĚŽKÉ'),text('Two rings must share the same pulse before the ancient arch will light our descent. Synchronise them without disturbing the living roots.','Dva kruhy musí sdílet stejný impulz, než starý oblouk osvětlí sestup. Sladíme je bez narušení živých kořenů.'),text('The arch lights up. A safe descent leads toward the root chamber.','Oblouk se rozsvěcí. Bezpečný sestup vede ke kořenové komoře.'),text('The trail goes underground','Stopa vede pod zem'),text('Beneath the arch we find a hand-drawn expedition arrow and a sealed note: the caretaker listens below. We copy the route to Elysium and prepare for the descent.','Pod obloukem nacházíme ručně kreslenou šipku výpravy a zapečetěnou poznámku: správce naslouchá dole. Kopírujeme trasu Elysiu a připravujeme sestup.'),[[2,27],[4,27],[3,21]],33,28,33],
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>{
 const resonators=i===3?[{at:27,target:3}]:i===4?[{at:26,target:3},{at:45,target:4}]:[];
 const holes=i===1?[0,6,49,55]:[];
 const size=i>=3?64:56;
 return {id:'grove-'+slug,name,lesson:name,thought,result,room:title,action:text('Activate the grove system','Aktivuj systém porostu'),icon:'✦',x,y,moves,tileSet:'night',resonators,
 level:{cols:i>=3?8:7,rows:8,types:6,mask:Array.from({length:size},(_,n)=>!holes.includes(n)&&!resonators.some(r=>r.at===n))},
 ice:i<2?[]:i===2?[9,12,23,25,37,40]:i===3?[17,22,41,46]:[9,14,17,22,41,46,49,54],
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'.'+(i>=2?' Break all protective covers.':'')+(resonators.length?' Charge every resonator.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+csLabels[type]).join(', ')+'.'+(i>=2?' Rozbij všechny ochranné kryty.':'')+(resonators.length?' Nabij všechny rezonátory.':''))};
});
repairs.forEach(r=>{r.ice=spacedResonatorCovers(r.ice,r.resonators,r.level);});
export const groveDestination={nextScene:'night-root',nextLabel:'Enter the root chamber →',title,key:'nightGroveCompleted',system:'night-glade',chapter:text('CHAPTER 08 / THE NIGHT GARDEN','KAPITOLA 08 / NOČNÍ ZAHRADA'),hotspotOffset:0,image:'night-grove',restoredImage:'night-grove-restored',repairs,
 logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Night expedition log','Deník noční výpravy'),time:title,unlockAt:126+i})),
 complete:text('Grove decoded. The expedition trail leads to the root chamber below.','Porost rozluštěn. Stopa výpravy vede do kořenové komory pod námi.'),
 clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 34% 27% at '+r.x+'% '+r.y+'%, #000 30%, transparent 100%)')};
text('Enter the luminous grove →','Vstup do světélkujícího porostu →');text('Return to the landing glade →','Zpět na přistávací mýtinu →');
