import {spacedResonatorCovers} from './resonators.js';
export const nightTranslations={};
const text=(en,cs)=>(nightTranslations[en]=cs,en);
const title=text('The night garden · Landing glade','Noční zahrada · Přistávací mýtina');
const labels=['Coolant charges','Energy modules','Navigation prisms','Root nodes','Luminous pollen','Living seeds'];
const csLabels=['chladicích náplní','energetických modulů','navigačních hranolů','kořenových uzlů','světelného pylu','živých semen'];
text('Root node','Kořenový uzel');text('Root nodes','Kořenové uzly');text('Luminous pollen','Světelný pyl');
const rows=[
 ['markers',text('Light the landing markers','Rozsviť přistávací značky'),text('The relay has given us a safe bearing. Link these dormant markers to its pulse before anyone steps into the valley.','Stanice nám poskytla bezpečný směr. Než vstoupíme do údolí, připojíme spící značky k jejímu impulzu.'),text('A pale ring of landing lights marks the glade.','Přistávací světla vyznačují mýtinu světlým kruhem.'),text('A path below the relay','Cesta pod stanicí'),text('The relay remains our way home. Down here, the ground carries the same rhythm through buried roots. The lights respond without a command code.','Stanice zůstává naší cestou domů. Zde pod zemí přenášejí kořeny stejný rytmus. Světla reagují i bez příkazového kódu.'),[[1,24],[2,21]],24,50,74],
 ['drone',text('Restore the survey drone','Obnov průzkumnou sondu'),text('Someone left this drone beside the terrace. Repair its sensor and record the glowing pollen without disturbing the plants.','Někdo nechal vedle terasy tuto sondu. Opravíme její senzor a zaznamenáme světelný pyl, aniž bychom rušili rostliny.'),text('The drone wakes and illuminates the nearby foliage.','Sonda se probouzí a osvětluje okolní porost.'),text('A human serial number','Lidské sériové číslo'),text('The casing belongs to the missing expedition. Its last scan recorded living pollen responding to the relay. We collect only a small sample.','Plášť patří ztracené výpravě. Poslední snímek zaznamenal živý pyl reagující na stanici. Odebíráme jen malý vzorek.'),[[4,27],[1,21]],25,20,56],
 ['roots',text('Trace the root network','Zmapuj kořenovou síť'),text('The beacon is connected to living roots. Release the protective locks and follow their pattern instead of cutting a new cable route.','Maják je připojený k živým kořenům. Uvolníme ochranné pojistky a sledujeme jejich vzor, místo abychom řezali novou trasu kabelu.'),text('Warm root nodes glow beside the survey beacon.','Vedle průzkumného majáku září teplé kořenové uzly.'),text('Power without wires','Energie bez kabelů'),text('The nodes pass a gentle pulse from plant to plant. The expedition marked the strongest connections but left every root intact. We follow their example.','Uzly předávají jemný impulz mezi rostlinami. Výprava označila nejsilnější spoje, ale nechala všechny kořeny celé. Následujeme její příklad.'),[[3,27],[5,24]],27,83,46],
 ['bridge',text('Open the stream crossing','Otevři cestu přes potok'),text('The crossing responds to the resonator beside it. Match next to the ring to charge it, then the guide lights can lead us across.','Přechod reaguje na rezonátor vedle něj. Spojováním vedle kruhu ho nabijeme a naváděcí světla nás dovedou přes vodu.'),text('Turquoise lights mark a safe crossing into the garden.','Tyrkysová světla vyznačují bezpečný přechod do zahrady.'),text('Follow the water','Sledujte vodu'),text('A weathered survey tag repeats the instruction from the first garden: follow the water, leave the roots undisturbed. Fresh tracks continue into the night.','Zvětralá průzkumná značka opakuje pokyn z první zahrady: sledujte vodu, kořeny nechte na pokoji. Čerstvé stopy pokračují do noci.'),[[0,27],[3,24]],29,50,48],
 ['glade',text('Synchronise the glade · HARD','Slaď mýtinu · TĚŽKÉ'),text('The landing route, drone and crossing are ready. Synchronise both rings to keep a return signal while the garden wakes.','Přistávací cesta, sonda i přechod jsou připravené. Sladíme oba kruhy, abychom zachovali zpáteční signál při probouzení zahrady.'),text('The glade blooms with light. A trail leads deeper into the luminous grove.','Mýtina rozkvétá světlem. Stezka vede hlouběji do světélkujícího porostu.'),text('We are not the first visitors','Nejsme první návštěvníci'),text('The returning pulse carries a fragment of the expedition beacon. They came through this glade and continued deeper. We send our findings to Elysium before following.','Vracející se impulz obsahuje útržek majáku výpravy. Prošli touto mýtinou a pokračovali dál. Než je následujeme, posíláme zjištění Elysiu.'),[[4,30],[5,27]],32,50,38],
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>{
 const resonators=i===3?[{at:27,target:3}]:i===4?[{at:26,target:3},{at:45,target:3}]:[];
 const size=i>=3?64:56;
 return {id:'night-'+slug,name,lesson:name,thought,result,room:title,action:text('Restore the garden system','Obnov systém zahrady'),icon:'✦',x,y,moves,tileSet:i===0?'research':i===1?'night-pollen':'night',resonators,
 level:{cols:i>=3?8:7,rows:8,types:6,mask:Array.from({length:size},(_,n)=>!resonators.some(r=>r.at===n))},
 ice:i<2?[]:i===2?[16,18,30,32]:i===3?[18,21,42,45]:[9,14,33,38,49,54],
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'.'+(i>=2?' Break all protective covers.':'')+(resonators.length?' Charge every resonator.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+csLabels[type]).join(', ')+'.'+(i>=2?' Rozbij všechny ochranné kryty.':'')+(resonators.length?' Nabij všechny rezonátory.':''))};
});
repairs.forEach(r=>{r.ice=spacedResonatorCovers(r.ice,r.resonators,r.level);});
export const nightDestination={title,key:'nightGladeCompleted',system:'fading-relay',chapter:text('CHAPTER 08 / THE NIGHT GARDEN','KAPITOLA 08 / NOČNÍ ZAHRADA'),nextScene:'night-grove',nextLabel:'Enter the luminous grove →',hotspotOffset:0,image:'night-glade',restoredImage:'night-glade-restored',repairs,
 logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Night expedition log','Deník noční výpravy'),time:title,unlockAt:121+i})),
 complete:text('Landing glade secured. The luminous grove is our next destination.','Přistávací mýtina zajištěna. Dalším cílem je světélkující porost.'),
 clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 38% 30% at '+r.x+'% '+r.y+'%, #000 30%, transparent 100%)')};
text('Descend to the night garden →','Sestup do Noční zahrady →');text('Return to the relay →','Zpět k retranslační stanici →');

