import {spacedResonatorCovers} from './resonators.js';
export const refugeHomesTranslations={};
const text=(en,cs)=>(refugeHomesTranslations[en]=cs,en);
const title=text('The refuge residential block','Obytný blok Útočiště');
const labels=['Coolant charges','Energy modules','Navigation prisms','Air filter modules','Supply capsules','Living seeds'];
const csLabels=['chladicích náplní','energetických modulů','navigačních hranolů','filtračních modulů','zásobovacích kapslí','živých semen'];
const rows=[
 ['air',text('Restore clean air','Obnov čistý vzduch'),text('The entry is safe, but the rooms still breathe through emergency filters. Restore the main circulation before anyone sleeps here.','Vstup je bezpečný, ale místnosti stále využívají nouzové filtry. Než tu někdo usne, obnovíme hlavní oběh.'),text('Fresh air flows through every sleeping compartment.','Čerstvý vzduch proudí do všech spacích oddílů.'),text('A place kept ready','Místo připravené pro návrat'),text('The filters were serviced before departure. This was a temporary absence: the expedition expected to come home.','Filtry byly servisované před odletem. Mělo jít o krátkou nepřítomnost: výprava počítala s návratem domů.'),[[3,27],[1,24]],27,20,36],
 ['water',text('Restart the water recycler','Spusť recyklaci vody'),text('Recover the cooling charges and release the recycler covers. We need clean water without spending the ship reserve.','Získáme chladicí náplně a uvolníme kryty recyklace. Potřebujeme čistou vodu bez čerpání lodní rezervy.'),text('The reservoir fills with clean recycled water.','Nádrž se plní čistou recyklovanou vodou.'),text('Every drop returns','Každá kapka se vrací'),text('A handwritten maintenance list pairs each visitor with a water allowance. The refuge was built for a small crew, not an endless population.','Ručně psaný servisní seznam přiděluje každému návštěvníkovi dávku vody. Útočiště vzniklo pro malou posádku, ne pro nekonečnou populaci.'),[[0,30],[3,24]],28,16,56],
 ['warmth',text('Balance the heating loop','Vyvaž topný okruh'),text('Charge the thermal regulator beside the heating pipes. Keep the sleeping area warm without overheating the seed reserve.','Nabijeme tepelný regulátor vedle topných trubek. Spací prostor musí být teplý, zásoba semen se však nesmí přehřát.'),text('A steady warmth spreads through the residential block.','Obytným blokem se šíří stálé teplo.'),text('Two temperatures','Dvě teploty'),text('The seed cabinet shares power with the bunks, but has its own thermostat. Even in an emergency, they protected what could grow next.','Skříň semen sdílí napájení s lůžky, ale má vlastní termostat. I v nouzi chránili to, co jednou může vyrůst.'),[[1,30],[5,24]],30,86,60],
 ['bunks',text('Prepare the sleeping compartments','Připrav spací oddíly'),text('Unlock the bunk covers and unpack the sealed supply capsules. Leave every berth ready for the rescue team.','Odemkneme kryty lůžek a rozbalíme uzavřené zásobovací kapsle. Připravíme každé místo pro záchranný tým.'),text('The bunks are lit and supplied. There is room for the returning crew.','Lůžka jsou osvětlená a vybavená. Pro vracející se posádku je místo.'),text('Names on the bunks','Jména na lůžkách'),text('The bunks still carry their owners’ names. One spare berth was marked for a rescued passenger. Their journey had a purpose beyond exploration.','Na lůžkách stále zůstávají jména majitelů. Jedno náhradní místo bylo označeno pro zachráněného pasažéra. Jejich cesta měla účel přesahující průzkum.'),[[4,33],[1,24]],29,84,40],
 ['ready',text('Secure the living block · HARD','Zajisti obytný blok · TĚŽKÉ'),text('Synchronise the safety ring and clear the remaining covers. Connect the room lights to the refuge beacon so the crew can see home from orbit.','Sladíme bezpečnostní kruh a uvolníme zbývající kryty. Napojíme osvětlení na maják Útočiště, aby posádka viděla domov už z oběžné dráhy.'),text('The living block is ready. A medical request waits in the expedition records.','Obytný blok je připravený. V záznamech výpravy čeká žádost o lékařskou pomoc.'),text('Home is waiting','Domov čeká'),text('Air, water, warmth and beds are ready. The next unopened manifest is labelled medical bay: someone aboard the rescue craft will need more than a safe landing.','Vzduch, voda, teplo i lůžka jsou připravené. Další neotevřený seznam nese označení ošetřovna: někdo na záchranné lodi bude potřebovat víc než bezpečné přistání.'),[[3,27],[4,27],[2,24]],34,50,54]
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>{
 const cols=i>=2?8:7,size=cols*8,resonators=i===2?[{at:27,target:3}]:i===4?[{at:27,target:4}]:[];
 const holes=i===1?[0,6,49,55]:[];
 const level={cols,rows:8,types:6,mask:Array.from({length:size},(_,n)=>!holes.includes(n)&&!resonators.some(r=>r.at===n))};
 const ice=spacedResonatorCovers(i===0?[9,12,37,40]:i===1?[9,12,23,25]:i===2?[9,14,49,54]:i===3?[9,14,25,30,49,54]:[9,14,41,46,49,54],resonators,level);
 return {id:'refuge-homes-'+slug,name,lesson:name,thought,result,room:title,action:text('Restore the living block','Obnov obytný blok'),icon:'✦',x,y,moves,tileSet:'refuge',level,ice,resonators,
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'. Break all protective covers.'+(resonators.length?' Charge every resonator.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+csLabels[type]).join(', ')+'. Rozbij všechny ochranné kryty.'+(resonators.length?' Nabij všechny rezonátory.':''))};
});
export const refugeHomes={nextScene:'refuge-medical',title,key:'refugeHomesCompleted',system:'refuge-dock',chapter:text('CHAPTER 09 / THE REFUGE','KAPITOLA 09 / ÚTOČIŠTĚ'),hotspotOffset:0,image:'refuge-homes',restoredImage:'refuge-homes-restored',repairs,
 logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Refuge expedition log','Deník výpravy / Útočiště'),time:title,unlockAt:146+i})),
 complete:text('The living block is ready for the expedition return.','Obytný blok je připravený pro návrat výpravy.'),nextLabel:text('Enter the medical bay →','Vstup do ošetřovny →'),
 clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 34% 27% at '+r.x+'% '+r.y+'%, #000 30%, transparent 100%)')};
text('Enter the residential block →','Vstup do obytného bloku →');
