import {spacedResonatorCovers} from './resonators.js';
export const refugeMedicalTranslations={};
const text=(en,cs)=>(refugeMedicalTranslations[en]=cs,en);
const title=text('The refuge medical bay','Ošetřovna Útočiště');
const labels=['Coolant charges','Energy modules','Navigation prisms','Air filter modules','Supply capsules','Living seeds'];
const csLabels=['chladicích náplní','energetických modulů','navigačních hranolů','filtračních modulů','zásobovacích kapslí','živých semen'];
const rows=[
 ['sterile',text('Restore the sterile circuit','Obnov sterilní okruh'),text('The refuge has air and beds. Now clean the medical circuit before opening its sealed supplies.','Útočiště má vzduch i lůžka. Než otevřeme uzavřené zásoby, vyčistíme okruh ošetřovny.'),text('Filtered air reaches the treatment area.','Filtrovaný vzduch proudí do ošetřovny.'),text('A room kept sealed','Uzavřená místnost'),text('The medical bay was sealed deliberately. The crew preserved a clean room for whoever their rescue flight brought home.','Ošetřovna byla uzavřena záměrně. Posádka chránila čistou místnost pro ty, které přiveze záchranný let.'),[[3,27],[1,24]],28,22,33],
 ['supplies',text('Recover the medical supplies','Získej zdravotnické zásoby'),text('Release the cabinet covers and check the supply capsules. Keep the medicines cool while the power returns.','Uvolníme kryty skříně a prověříme zásobovací kapsle. Léčiva musí zůstat v chladu i během obnovy napájení.'),text('The supplies are sorted and the cold cabinet is stable.','Zásoby jsou roztříděné a chladicí skříň funguje.'),text('One extra kit','Jedna souprava navíc'),text('The manifest lists one more emergency kit than there are crew bunks. They expected to bring someone back, not simply return alone.','Seznam uvádí o jednu nouzovou soupravu víc, než je lůžek posádky. Počítali s tím, že někoho přivezou, ne pouze s vlastním návratem.'),[[4,30],[0,27]],29,78,33],
 ['diagnostics',text('Calibrate the diagnostic station','Seřiď diagnostické pracoviště'),text('Charge the diagnostic regulator and recover the archived sensor settings. A usable reading matters more than a bright screen.','Nabijeme diagnostický regulátor a obnovíme nastavení senzorů. Potřebujeme spolehlivé měření, ne jen svítící obrazovku.'),text('The diagnostic station passes its calibration check.','Diagnostické pracoviště prošlo kontrolou nastavení.'),text('The last request','Poslední žádost'),text('A saved request asks for treatment after prolonged exposure to the night garden. It contains no patient name, only the rescue craft call sign.','Uložená žádost požaduje péči po dlouhém pobytu v Noční zahradě. Neobsahuje jméno pacienta, pouze volací znak záchranné lodi.'),[[2,27],[1,30]],31,22,58],
 ['culture',text('Restart the recovery culture','Obnov regenerační kulturu'),text('Bring the small seed culture back online and stabilise its cooling. The refuge greenhouse kept this reserve alive for medical use.','Obnovíme malou semennou kulturu a její chlazení. Skleník Útočiště chránil tuto zásobu pro potřeby ošetřovny.'),text('The culture is stable and the treatment berth is ready.','Kultura je stabilní a ošetřovací lůžko připravené.'),text('What the garden can give','Co může zahrada dát'),text('The expedition recorded a useful recovery compound in the living seeds. Their notes insist on measured doses: the garden is a resource to understand, not a miracle to trust blindly.','Výprava zaznamenala užitečnou regenerační látku v živých semenech. Poznámky trvají na přesném dávkování: zahradu je třeba poznat, ne slepě věřit jejím zázrakům.'),[[5,30],[0,27]],30,78,58],
 ['ready',text('Prepare the refuge for return · HARD','Připrav Útočiště na návrat · TĚŽKÉ'),text('Synchronise the medical reserve with the refuge beacon. Send one clear message: landing, shelter and treatment are ready.','Sladíme zdravotnickou rezervu s majákem Útočiště. Odešleme jasnou zprávu: přistání, přístřeší i péče jsou připravené.'),text('The refuge is ready. The rescue craft acknowledges our beacon and sends a new bearing.','Útočiště je připravené. Záchranná loď potvrzuje náš maják a posílá nové souřadnice.'),text('A home to return to','Domov pro návrat'),text('The reply is short: REFUGE RECEIVED. RETURN CORRIDOR OBSTRUCTED. NEW BEARING ATTACHED. We have restored a home for the expedition. Next, we must find a safe way to bring them back.','Odpověď je stručná: ÚTOČIŠTĚ POTVRZENO. NÁVRATOVÝ KORIDOR ZABLOKOVÁN. NOVÉ SOUŘADNICE PŘILOŽENY. Obnovili jsme výpravě domov. Příště musíme najít bezpečnou cestu pro její návrat.'),[[3,27],[4,27],[1,27]],35,50,79]
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>{
 const cols=i<2?7:8,size=cols*8,resonators=i===2?[{at:27,target:3}]:i===4?[{at:27,target:4}]:[];
 const holes=i===1?[0,6,49,55]:[];
 const level={cols,rows:8,types:6,mask:Array.from({length:size},(_,n)=>!holes.includes(n)&&!resonators.some(r=>r.at===n))};
 const ice=spacedResonatorCovers(i<2?[9,12,37,40]:i===2?[9,14,49,54]:i===3?[9,14,25,30,49,54]:[9,14,41,46,49,54],resonators,level);
 return {id:'refuge-medical-'+slug,name,lesson:name,thought,result,room:title,action:text('Restore the medical bay','Obnov ošetřovnu'),icon:'✚',x,y,moves,tileSet:'refuge',level,ice,resonators,
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'. Break all protective covers.'+(resonators.length?' Charge every resonator.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+csLabels[type]).join(', ')+'. Rozbij všechny ochranné kryty.'+(resonators.length?' Nabij všechny rezonátory.':''))};
});
export const refugeMedical={title,key:'refugeMedicalCompleted',system:'refuge-homes',chapter:text('CHAPTER 09 / THE REFUGE','KAPITOLA 09 / ÚTOČIŠTĚ'),hotspotOffset:0,image:'refuge-medical',restoredImage:'refuge-medical-restored',repairs,
 logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Refuge medical log','Deník ošetřovny / Útočiště'),time:title,unlockAt:151+i})),
 complete:text('The refuge is ready for the rescue craft. A new bearing waits in the ship log.','Útočiště je připravené pro záchrannou loď. Nové souřadnice čekají v lodním deníku.'),nextLabel:text('Return to the residential block →','Zpět do obytného bloku →'),
 clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 34% 27% at '+r.x+'% '+r.y+'%, #000 30%, transparent 100%)')};
text('Enter the medical bay →','Vstup do ošetřovny →');
