import {spacedResonatorCovers} from './resonators.js';
export const refugeTranslations={};
const text=(en,cs)=>(refugeTranslations[en]=cs,en);
const title=text('The refuge arrival dock','Příletový dok Útočiště');
const originalLabels=['Coolant charges','Energy modules','Navigation prisms','Root nodes','Luminous pollen','Living seeds'];
const originalCs=['chladicích náplní','energetických modulů','navigačních hranolů','kořenových uzlů','světelného pylu','živých semen'];
const rows=[
 ["beacon",text("Reconnect the arrival beacon","Připoj příletový maják"),text("The caretaker coordinates brought us here. Keep a clear signal to the ship while we inspect the silent dock.","Souřadnice správce nás dovedly sem. Během prohlídky tichého doku zachováme jasný signál k lodi."),text("The dock beacon marks a safe approach.","Maják doku označuje bezpečný přílet."),text("A shelter in the dark","Úkryt ve tmě"),text("The Refuge is smaller than Elysium: a practical shelter built by the expedition. Its departure log lists a rescue journey, not an evacuation.","Útočiště je menší než Elysium: praktický úkryt postavený výpravou. Odletový deník uvádí záchrannou cestu, nikoli evakuaci."),[[2, 27], [1, 24]],25,20,61],
 ["filters",text("Replace the intake filters","Vyměň vstupní filtry"),text("Air filter modules replace root nodes here. Fit fresh cartridges and restore the intake before pressurising the entry.","Kořenové uzly zde nahrazují filtrační moduly. Osadíme čerstvé vložky a obnovíme sání před natlakováním vstupu."),text("The intake filters circulate clean air.","Vstupní filtry rozvádějí čistý vzduch."),text("Air for their return","Vzduch pro jejich návrat"),text("The cartridges were packed for a return visit. Someone expected this refuge to welcome the rescue team home.","Vložky byly připravené pro návrat. Někdo počítal s tím, že tento úkryt přivítá záchranný tým doma."),[[3, 30], [0, 24]],27,80,46],
 ["supplies",text("Recover the dock supplies","Obnov zásoby doku"),text("Supply capsules replace luminous pollen. Release the locker covers and check the sealed emergency packs.","Světelný pyl nahrazují zásobovací kapsle. Uvolníme kryty skříně a zkontrolujeme uzavřené nouzové balíčky."),text("The locker opens with intact emergency supplies.","Skříň se otevírá s neporušenými nouzovými zásobami."),text("Enough to share","Dost ke sdílení"),text("Water and sealed rations remain inside. The team left a portion for whoever followed their signal; we reserve it for the next arrivals.","Uvnitř zůstala voda a uzavřené potraviny. Tým nechal část pro toho, kdo půjde za signálem; rezervujeme ji dalším příchozím."),[[4, 30], [1, 24]],28,78,72],
 ["walkway",text("Secure the entrance walkway","Zajisti vstupní lávku"),text("Restore the guide lights and synchronise the old safety ring. The path must remain usable in both directions.","Obnovíme vodicí světla a sladíme starý bezpečnostní kruh. Cesta musí zůstat průchozí oběma směry."),text("The walkway lights form a safe path to the airlock.","Světla lávky vytvářejí bezpečnou cestu k přechodové komoře."),text("The same route back","Stejná cesta zpět"),text("The safety ring records every visitor and preserves a return route. Its last group left together, carrying medical equipment.","Bezpečnostní kruh zaznamenává každého návštěvníka a zachovává zpáteční trasu. Poslední skupina odešla společně s lékařským vybavením."),[[2, 27], [3, 27]],30,43,48],
 ["airlock",text("Pressurise the refuge entry · HARD","Natlakuj vstup Útočiště · TĚŽKÉ"),text("Synchronise both pressure rings, clear the covers and prepare the entry for people rather than just instruments.","Sladíme oba tlakové kruhy, odstraníme kryty a připravíme vstup pro lidi, nejen pro přístroje."),text("The entry is sealed and pressurised. The residential block lies beyond.","Vstup je utěsněný a natlakovaný. Za ním leží obytný blok."),text("A home waiting","Domov čeká"),text("Warm lights appear behind the airlock. We have made a safe entrance; the next task is to restore the rooms for the expedition return.","Za přechodovou komorou se objevují teplá světla. Zajistili jsme bezpečný vstup; dalším úkolem bude obnovit místnosti pro návrat výpravy."),[[3, 30], [0, 30], [4, 24]],34,62,39],

];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>{
 const labels=originalLabels.map((label,n)=>n===3&&i>=1?'Air filter modules':n===4&&i>=2?'Supply capsules':label);
 const csLabels=originalCs.map((label,n)=>n===3&&i>=1?'filtračních modulů':n===4&&i>=2?'zásobovacích kapslí':label);
 const resonators=i===3?[{at:27,target:3}]:i===4?[{at:26,target:3},{at:45,target:4}]:[];
 const holes=i===1?[0,6,49,55]:[];
 const size=i>=3?64:56;
 return {id:'refuge-dock-'+slug,name,lesson:name,thought,result,room:title,action:text('Restore the refuge entry','Obnov vstup Útočiště'),icon:'✦',x,y,moves,tileSet:i===0?'night':i===1?'refuge-filter':'refuge',resonators,
 level:{cols:i>=3?8:7,rows:8,types:6,mask:Array.from({length:size},(_,n)=>!holes.includes(n)&&!resonators.some(r=>r.at===n))},
 ice:i===0?[9,12,37,40]:i===1?[9,12,23,25]:i===2?[9,12,23,25,37,40]:i===3?[17,22,41,46]:[9,14,17,22,41,46,49,54],
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'. Break all protective covers.'+(resonators.length?' Charge every resonator.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+csLabels[type]).join(', ')+'. Rozbij všechny ochranné kryty.'+(resonators.length?' Nabij všechny rezonátory.':''))};
});
repairs.forEach(r=>{r.ice=spacedResonatorCovers(r.ice,r.resonators,r.level);});
export const refugeDock={nextScene:'refuge-homes',nextLabel:text('Enter the residential block →','Vstup do obytného bloku →'),title,key:'refugeDockCompleted',system:'night-sanctuary',chapter:text('CHAPTER 09 / THE REFUGE','KAPITOLA 09 / ÚTOČIŠTĚ'),hotspotOffset:0,image:'refuge-dock',restoredImage:'refuge-dock-restored',repairs,
 logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Refuge expedition log','Deník výpravy / Útočiště'),time:title,unlockAt:141+i})),
 complete:text('Arrival dock secured. The residential block is our next destination.','Příletový dok zajištěn. Dalším cílem je obytný blok.'),
 clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 34% 27% at '+r.x+'% '+r.y+'%, #000 30%, transparent 100%)')};
text('Travel to the Refuge →','Vydej se do Útočiště →');text('Return to the caretaker sanctuary →','Zpět do svatyně správce →');
text('Air filter module','Filtrační modul');text('Air filter modules','Filtrační moduly');text('Supply capsule','Zásobovací kapsle');text('Supply capsules','Zásobovací kapsle');
