export const relayTranslations={};
const text=(en,cs)=>(relayTranslations[en]=cs,en);
const title=text('The silent relay','Ztichlá retranslační stanice');
const labels=['Coolant charges','Energy modules','Navigation prisms','Alloy components','Research samples','Living seeds'];
const rows=[
 ['resonator',text('Wake the signal resonator','Probuď signální rezonátor'),text('This receiver needs a rhythm, not more power. Make matches beside the ring on the board. Each matching wave adds one impulse.','Tento přijímač potřebuje rytmus, ne více energie. Spojuj kameny vedle kruhu na desce. Každá vlna spojení přidá jeden impulz.'),text('The first resonator answers. The relay can hear us.','První rezonátor odpovídá. Stanice nás slyší.'),text('Listening before speaking','Nejprve naslouchat'),text('The station uses the same pulse pattern as the living map. A patient sequence wakes its receiver without disturbing the faint human signal beneath the noise.','Stanice používá stejný rytmus impulzů jako živá mapa. Trpělivá posloupnost probudí přijímač, aniž by narušila slabý lidský signál pod šumem.'),[[1,18]],24,23,51,[{at:24,target:2}]],
 ['dish',text('Align the relay dish','Nasměruj anténu'),text('Two resonators must agree before the dish can lock onto the fading world. Charge both through neighbouring matches.','Dva rezonátory se musí sladit, než anténa zaměří Zhasínající svět. Nabij oba spojováním sousedních kamenů.'),text('The dish turns toward the night side of the planet.','Anténa se otáčí k noční straně planety.'),text('A narrow bearing','Úzký směr'),text('The human call sign repeats from a valley on the night side. We send the bearing to Elysium and keep the return channel open.','Lidský volací znak se opakuje z údolí na noční straně. Posíláme směr Elysiu a necháváme zpáteční kanál otevřený.'),[[2,24]],27,82,54,[{at:26,target:2},{at:45,target:2}]],
 ['recording',text('Recover the broken message','Obnov přerušenou zprávu'),text('Release the protective covers and separate the expedition recording from the caretaker pulses.','Uvolni ochranné kryty a odděl záznam výpravy od impulzů správce.'),text('The recording identifies a refuge beyond the dark garden.','Záznam označuje útočiště za temnou zahradou.'),text('Still holding on','Stále se držíme'),text('A damaged recording says: the refuge is sealed, follow the irrigation lights. The timestamp is uncertain. We have a destination, but no promise that anyone is still there.','Poškozený záznam říká: útočiště je uzavřené, sledujte světla zavlažování. Časová značka je nejistá. Máme cíl, ale žádný příslib, že tam stále někdo je.'),[[2,24],[4,18]],29,58,62,[{at:24,target:3}]],
 ['descent',text('Secure the descent corridor · HARD','Zajisti sestupový koridor · TĚŽKÉ'),text('Synchronize the relay, clear the interlocks and mark a safe route through the clouds. Elysium will follow our descent.','Synchronizuj stanici, uvolni pojistky a vyznač bezpečnou cestu mraky. Elysium bude sledovat náš sestup.'),text('The descent corridor is marked. The night garden is the next stop.','Sestupový koridor je vyznačený. Další zastávkou je Noční zahrada.'),text('Lights below the clouds','Světla pod mraky'),text('The relay now holds both our home channel and the refuge bearing. A broken chain of irrigation lights appears below the clouds. That is where the expedition went.','Stanice nyní drží spojení s domovem i směr k útočišti. Pod mraky se objevuje přerušený řetězec zavlažovacích světel. Tudy výprava pokračovala.'),[[1,24],[2,24]],32,72,29,[{at:26,target:3},{at:45,target:3}]]
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y,resonators],i)=>({id:'relay-'+slug,name,lesson:name,thought,result,room:title,action:text('Restore the relay system','Obnov systém stanice'),icon:'✦',x,y,moves,tileSet:'research',resonators,
 level:{cols:resonators.length>1?8:7,rows:resonators.length>1?8:7,types:6,mask:Array.from({length:resonators.length>1?64:49},(_,n)=>!resonators.some(r=>r.at===n))},ice:i<2?[]:i===2?[15,19,29,33]:[9,12,37,40,44,46],
 goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((n,g)=>n+g[1],0),targetType:null,
 objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'. Charge every resonator.'+(i>=2?' Break all protective covers.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+['chladicích náplní','energetických modulů','navigačních hranolů','slitinových dílů','výzkumných vzorků','živých semen'][type]).join(', ')+'. Nabij všechny rezonátory.'+(i>=2?' Rozbij všechny ochranné kryty.':''))}));
export const relayDestination={title,key:'relayCompleted',system:'elysium',chapter:text('CHAPTER 07 / THE FADING WORLD','KAPITOLA 07 / ZHASÍNAJÍCÍ SVĚT'),image:'fading-relay',restoredImage:'fading-relay',dimInitial:true,repairs,logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Rescue expedition log','Deník záchranné výpravy'),time:title,unlockAt:121+i})),complete:text('Relay secured. The night garden awaits below.','Stanice zajištěna. Dole čeká Noční zahrada.'),clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 42% 34% at '+r.x+'% '+r.y+'%, #000 35%, transparent 100%)')};
text('Travel to the silent relay →','Vyrazit k retranslační stanici →');
text('Resonators','Rezonátory');text('Match beside each ring to charge it. Blasts do not charge rings.','Spojuj kameny vedle každého kruhu. Výbuchy kruhy nenabíjejí.');

text('Charge the ring','Nabij kruh');
text('Match 3 so that at least one matched tile touches the ring above, below, left or right. Each match adds +1. Blasts do not count.','Spoj 3 kameny tak, aby se alespoň jeden dotýkal kruhu nahoře, dole, vlevo nebo vpravo. Každé spojení přidá +1. Výbuchy se nepočítají.');
text('Got it','Rozumím');text('Resonator +1','Rezonátor +1');
