export const researchTranslations={};
const text=(en,cs)=>(researchTranslations[en]=cs,en);
const title=text('The changing map','Mapa, která se mění');
const labels=['Coolant charges','Energy modules','Navigation prisms','Alloy components','Research samples','Living seeds'];
const rows=[
 ['unpack',text('Connect the seed archive','Připoj semenný archiv'),text('Back on Elysium, the garden records belong in a protected reader. Keep the original intact while we make a working copy.','Zpět na Elysiu uložíme záznamy zahrady do chráněné čtečky. Originál zachováme a vytvoříme pracovní kopii.'),text('The archive is connected. Its living patterns are safely copied.','Archiv je připojený. Jeho živé vzory jsou bezpečně zkopírované.'),text('Home with a question','Doma s otázkou'),text('The station lights feel familiar now. We brought no treasure from the ring, only a seed and a map that will not hold still. The garden remains awake behind us.','Světla stanice už působí důvěrně. Z prstence jsme nepřivezli poklad, jen semeno a mapu, která se neustále mění. Zahrada za námi zůstává probuzená.'),[[2,24],[3,21]],23,18,75],
 ['chamber',text('Prepare the specimen chamber','Připrav komoru pro vzorek'),text('The seed needs its own water and atmosphere. Build a sealed chamber before asking it to grow.','Semeno potřebuje vlastní vodu a atmosféru. Než je necháme růst, připravíme uzavřenou komoru.'),text('The specimen chamber is stable. A small shoot unfolds.','Komora pro vzorek je stabilní. Rozvíjí se malý výhonek.'),text('A guest, not a resource','Host, nikoli zásoba'),text('The seed reacts to light from the archive. We keep it isolated from the biosphere and copy every reading. It is not fuel for the station; it is part of the message.','Semeno reaguje na světlo archivu. Necháváme je oddělené od biosféry a ukládáme všechna měření. Není palivem pro stanici, je součástí zprávy.'),[[0,24],[5,24]],24,17,48],
 ['decode',text('Decode the living map','Rozlušti živou mapu'),text('The changes repeat in a pattern. Compare the specimen readings with the archive instead of treating them as noise.','Změny se opakují podle vzoru. Porovnáme měření vzorku s archivem, místo abychom je považovali za šum.'),text('A network of garden worlds resolves above the table.','Nad stolem se vykresluje síť zahradních světů.'),text('The map is a status report','Mapa je zpráva o stavu'),text('The points are not moving. Their brightness reports the condition of distant gardens. One point is fading while its neighbours remain steady.','Body se nepohybují. Jejich jas hlásí stav vzdálených zahrad. Jeden bod pohasíná, zatímco jeho sousedé zůstávají stabilní.'),[[2,27],[4,24]],27,53,58],
 ['compare',text('Trace the human signal','Vystopuj lidský signál'),text('Compare the fading point with the original distress recording. We need a real match, not a hopeful guess.','Porovnáme pohasínající bod s původním nouzovým záznamem. Potřebujeme skutečnou shodu, ne nadějný odhad.'),text('The expedition identifier matches the fading garden.','Identifikátor výpravy odpovídá pohasínající zahradě.'),text('A voice among the roots','Hlas mezi kořeny'),text('Under the caretaker pulse is a human call sign from the missing expedition. The message is incomplete, but its source is clear. Someone reached that world.','Pod impulzem správce je lidský volací znak ztracené výpravy. Zpráva není úplná, ale její zdroj je jasný. Někdo na ten svět dorazil.'),[[1,24],[2,27],[4,18]],29,81,46],
 ['route',text('Chart the rescue route · HARD','Vytyč záchrannou trasu · TĚŽKÉ'),text('Plot a route through the old relay to the dark garden. Leave Elysium listening and preserve the return coordinates.','Vytyčíme cestu přes starou retranslační stanici do temné zahrady. Elysium necháme naslouchat a zachováme zpáteční souřadnice.'),text('The next expedition is charted: relay, night garden, expedition refuge.','Další výprava je zmapovaná: retranslační stanice, noční zahrada, útočiště výpravy.'),text('A destination with a purpose','Cíl, který má smysl'),text('We are no longer following a mystery without an end. The next route leads to a failing garden and a human signal. Elysium will remain our listening post. First the relay, then the garden, then the refuge.','Už nesledujeme záhadu bez konce. Další cesta vede k selhávající zahradě a lidskému signálu. Elysium zůstane naším naslouchajícím stanovištěm. Nejprve retranslační stanice, potom zahrada a nakonec útočiště.'),[[2,30],[4,24],[5,24]],32,51,42]
];
const repairs=rows.map(([slug,name,thought,result,logTitle,logText,goals,moves,x,y],i)=>({id:'research-'+slug,name,lesson:name,thought,result,room:title,action:text('Complete the research','Dokonči výzkum'),icon:'✦',x,y,moves,tileSet:'research',level:{cols:7,rows:i>=3?8:7,types:6,...(i===1?{mask:Array.from({length:49},(_,n)=>![0,6,42,48].includes(n))}:{})},ice:i<2?[]:i===4?[9,12,22,26,37,40,44,46]:[15,19,29,33],goals:goals.map(([type,target])=>({type,target,label:labels[type]})),target:goals.reduce((sum,g)=>sum+g[1],0),targetType:null,objective:text('Collect '+goals.map(([type,n])=>n+' '+labels[type].toLowerCase()).join(', ')+'.'+(i>=2?' Break all protective covers.':''),'Nasbírej '+goals.map(([type,n])=>n+' '+['chladicích náplní','energetických modulů','navigačních hranolů','slitinových dílů','výzkumných vzorků','živých semen'][type]).join(', ')+'.'+(i>=2?' Rozbij všechny ochranné kryty.':''))}));
export const researchDestination={title,key:'researchCompleted',system:'elysium',chapter:text('ELYSIUM / RESEARCH','ELYSIUM / VÝZKUM'),image:'elysium-research',restoredImage:'elysium-research',dimInitial:true,repairs,logs:rows.map((r,i)=>({id:repairs[i].id+'-log',repair:repairs[i].id,title:r[4],text:r[5],source:text('Elysium research log','Výzkumný deník Elysia'),time:title,unlockAt:116+i})),complete:text('Rescue route charted. The fading world is our next destination.','Záchranná trasa zmapována. Dalším cílem je Zhasínající svět.'),clips:repairs.map(()=> 'inset(0)'),restorationMasks:repairs.map(r=>'radial-gradient(ellipse 42% 34% at '+r.x+'% '+r.y+'%, #000 35%, transparent 100%)')};
text('Return to Elysium · Research →','Zpět na Elysium · Výzkum →');
text('Research the living map →','Prozkoumat živou mapu →');
text('Navigation prism','Navigační hranol');text('Research sample','Výzkumný vzorek');text('Living seed','Živé semeno');
text('Navigation prisms','Navigační hranoly');text('Research samples','Výzkumné vzorky');text('Living seeds','Živá semena');
