export const tutorialTopics = {
 pulse:{icon:'✺',en:['Pulse blast','You just used Pulse: it clears a 3×3 area and breaks protective covers. Create it by matching 4 in a line or a T/L shape. Tapping it costs one move; chained blasts are free.'],cs:['Výbuch Pulse','Právě jsi použil Pulse: vyčistí oblast 3×3 a rozbije ochranné kryty. Vytvoříš ho spojením 4 v řadě nebo do T/L. Klepnutí stojí jeden tah; řetězové výbuchy jsou zdarma.']},
 nova:{icon:'✦',en:['Nova blast','You just used Nova: it clears its row and column and breaks protective covers. Create it by matching 5 or more in a line. Tapping it costs one move; chained blasts are free.'],cs:['Výbuch Nova','Právě jsi použil Novu: vyčistí svůj řádek a sloupec a rozbije ochranné kryty. Vytvoříš ji spojením 5 a více v řadě. Klepnutí stojí jeden tah; řetězové výbuchy jsou zdarma.']},
 laser:{icon:'⌖',en:['Laser','Laser hits one selected tile. A protective cover breaks first; the tile beneath stays. It uses one tool from your stock, not a move.'],cs:['Laser','Laser zasáhne jednu vybranou dlaždici. Ochranný kryt nejprve praskne; dlaždice pod ním zůstane. Spotřebuje jednu pomůcku ze zásoby, nikoli tah.']},
 shuffle:{icon:'⤨',en:['Shuffle','Shuffle rearranges uncovered tiles to offer new matches. It uses one tool from your stock, not a move.'],cs:['Míchání','Míchání přeskupí nezakryté dlaždice a nabídne nové kombinace. Spotřebuje jednu pomůcku ze zásoby, nikoli tah.']},
 swap:{icon:'⇄',en:['Swap','Swap exchanges two adjacent uncovered tiles even without a match. It uses one tool from your stock, not a move.'],cs:['Výměna','Výměna prohodí dvě sousední nezakryté dlaždice i bez kombinace. Spotřebuje jednu pomůcku ze zásoby, nikoli tah.']},
 beam:{icon:'➜',en:['Beam','Beam hits the entire selected row and can trigger charges. It uses one tool from your stock, not a move.'],cs:['Paprsek','Paprsek zasáhne celý vybraný řádek a může odpálit nálože. Spotřebuje jednu pomůcku ze zásoby, nikoli tah.']},
 emp:{icon:'✺',en:['EMP','EMP hits a 3×3 area around the selected tile and can trigger charges. It uses one tool from your stock, not a move.'],cs:['EMP','EMP zasáhne oblast 3×3 kolem vybrané dlaždice a může odpálit nálože. Spotřebuje jednu pomůcku ze zásoby, nikoli tah.']},
 charges: {icon:'✺',en:['Pulse & Nova','Match 4 in a line or a T/L shape to create Pulse (3×3 blast). Match 5 or more to create Nova (row and column). Tap a charge to activate it: this uses one move. Chain reactions are free.'],cs:['Pulse a Nova','Spoj 4 v řadě nebo do T/L a vytvoříš Pulse (výbuch 3×3). Spoj 5 a více a vznikne Nova (řádek a sloupec). Klepnutí na nálož stojí jeden tah. Řetězové reakce jsou zdarma.']},
 covers: {icon:'▣',en:['Protective covers','The tile beneath a cover is visible. Include it in a match of the same type to break the cover. That tile stays on the board for another match. Covered tiles cannot be swapped; blasts can also break covers.'],cs:['Ochranné kryty','Pod krytem vidíš dlaždici. Zapoj ji do spojení stejného typu a kryt praskne. Dlaždice zůstane pro další spojení. Kryté dlaždice nelze přesouvat; kryty rozbíjí i výbuchy.']},
 resonators: {icon:'◎',en:['Charge the resonator','Match 3 so a matched tile touches the ring above, below, left or right. Each matching wave adds +1 per ring. Diagonals and direct blasts do not charge it. Charge every ring to its target.'],cs:['Nabij rezonátor','Spoj 3 tak, aby se spojená dlaždice dotýkala kruhu shora, zdola, zleva nebo zprava. Každá vlna spojení přidá kruhu +1. Úhlopříčka ani přímý výbuch ho nenabíjí. Nabij všechny kruhy na jejich cíl.']},
 helpers: {icon:'⌖',en:['Your tools','The five tools below the board are Laser, Shuffle, Swap, Beam and EMP. Select a tool, then its target (Shuffle acts immediately). Using a tool costs stock, not a move. Stock is shared across levels. AD offers a rewarded ad when stock is empty.'],cs:['Tvoje pomůcky','Pod deskou jsou Laser, Míchání, Výměna, Paprsek a EMP. Vyber pomůcku a potom cíl (Míchání se provede hned). Použití spotřebuje zásobu, nikoli tah. Zásoby jsou společné pro všechny levely. AD nabídne reklamu za doplnění prázdné zásoby.']}
};
export const helperTutorials=['laser','shuffle','swap','beam','emp'];
export function initialTutorials({covers,resonators}){return [...(covers?['covers']:[]),...(resonators?['resonators']:[])];}
export function relevantTutorials({boosts,covers,resonators}){
 return [...(boosts?['charges']:[]),...(covers?['covers']:[]),...(resonators?['resonators']:[]),'helpers'];
}
export function readTutorials(storage,key){try{const value=JSON.parse(storage.getItem(key));return Array.isArray(value)?value.filter(id=>Object.hasOwn(tutorialTopics,id)):[];}catch{return [];}}
